### ISSUE TITLE
grr could support multiple issues

### ISSUE THREAD

**Issue by jlevon** [joyent/grr#13]
grr is so useful for me that I hate having do things manually just because my CR has more than one issue. It would be very useful if grr could take a comma-separated list of issues and assembled them for me.

**Comment by trentm** [comment]
- merged (pull #14) in commit 40bff97309d762ad8ea79c20771039272b575cb7
- tweaked in commit 12e990e415e27ee905a80d270abb254c11ef5c5a
- verbump to 1.8.0 in commit c4aa86dcc4787f7efb6bbfbaeee3b094c5d099cf
- tagged and published joyent-grr@1.8.0

Thanks for implementing this!

**Comment by trentm** [comment]
change log entry: https://github.com/joyent/grr/blob/master/CHANGES.md#180
